name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: docker pull 15labshub/cicd-pipeline:latest

    - name: Delete Old Docker Container
      run: docker rm -f cicd-pipeline-container || true

    - name: Run Docker Container
      run: docker run -d -p 8080:8080 --name cicd-pipeline-container 15labshub/cicd-pipeline

    - name: Wait for Container to Start
      run: |
        sleep 10  # Adjust the sleep duration based on your application startup time
        curl -f http://localhost:8080/ || exit 1
